version: '3.8'

services:
  convenience-store-app:
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env
      - .env.local
    restart: always
    container_name: convenience-store-app